# Generated by Django 3.2.9 on 2023-07-28 09:53

import Account.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('One', models.TextField(max_length=2000, null=True, verbose_name='متن اول')),
                ('Two', models.TextField(max_length=2000, null=True, verbose_name='متن دوم')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='VersesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(null=True, verbose_name='شماره آیه')),
                ('Persian', models.TextField(max_length=2000, null=True, verbose_name='فارسی')),
                ('English', models.TextField(max_length=2000, null=True, verbose_name='فارسی')),
                ('Arabic', models.TextField(max_length=2000, null=True, verbose_name='فارسی')),
                ('Soreh', models.TextField(max_length=100, null=True, verbose_name='فارسی')),
                ('Jose', models.TextField(max_length=100, null=True, verbose_name='فارسی')),
                ('Voice', models.ImageField(blank=True, null=True, upload_to='Voice/', validators=[Account.validators.validate_file_extension, Account.validators.validate_file_size], verbose_name='صوت')),
            ],
            options={
                'verbose_name': 'آیه',
                'verbose_name_plural': 'آیه ها',
            },
        ),
        migrations.CreateModel(
            name='PeopleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Read', models.JSONField(default=dict, help_text={'R_qoran': {'favnumbers': [], 'number': 0, 'numbers': []}}, null=True, verbose_name='آیه های خوانده شده')),
                ('ReadDetails', models.JSONField(default=dict, help_text={'d_qoran': {'count': 0, 'end': [], 'start': []}}, null=True, verbose_name='جزییات خوانده شده ها')),
                ('DailyRead', models.IntegerField(null=True, verbose_name='تعداد آیه در روز')),
                ('Chatid', models.CharField(blank=True, max_length=30, null=True, verbose_name='چت ایدی')),
                ('Lang', models.IntegerField(choices=[(1, 'فارسی'), (2, 'عربی'), (3, 'انگلیسی')], default=1, verbose_name='زبان')),
                ('People', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='people', to=settings.AUTH_USER_MODEL, verbose_name='کاربری')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
